/**
 * DocumentDrawer — Full-screen slide-in drawer for chapter / section navigation.
 * Matches the mockup: FRONT MATTER + CHAPTERS tree, Add Chapter button, close X.
 */
import React, { useRef, useEffect, memo, useCallback, useState } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, BackHandler,
  ScrollView, Animated, Easing, Dimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { C, F, S, R, shadows } from '@/constants/theme';
import type { Section, Chapter } from '@/services/api';

const { width: SCREEN_W } = Dimensions.get('window');
const DRAWER_W = Math.min(SCREEN_W * 0.82, 320);

// ── Types ──────────────────────────────────────────────────────────────────────

interface Props {
  visible: boolean;
  onClose: () => void;
  frontMatter: Section[];
  chapters: Chapter[];
  activeId: string | null;
  onSelect: (id: string) => void;
  onAddChapter: () => void;
  onDeleteChapter: (c: Chapter) => void;
  onRenameChapter: (c: Chapter) => void;
}

// ── Drawer ─────────────────────────────────────────────────────────────────────

export function DocumentDrawer({
  visible, onClose,
  frontMatter, chapters, activeId,
  onSelect, onAddChapter, onDeleteChapter, onRenameChapter,
}: Props) {
  const slideX  = useRef(new Animated.Value(-DRAWER_W)).current;
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (visible) {
      Animated.parallel([
        Animated.timing(slideX,  { toValue: 0,        duration: 280, easing: Easing.out(Easing.cubic), useNativeDriver: true }),
        Animated.timing(opacity, { toValue: 1,        duration: 200, useNativeDriver: true }),
      ]).start();
    } else {
      Animated.parallel([
        Animated.timing(slideX,  { toValue: -DRAWER_W, duration: 220, easing: Easing.in(Easing.quad), useNativeDriver: true }),
        Animated.timing(opacity, { toValue: 0,         duration: 180, useNativeDriver: true }),
      ]).start();
    }
  }, [visible]);

  useEffect(() => {
    if (visible) {
      const onBackPress = () => {
        onClose();
        return true;
      };
      const subscription = BackHandler.addEventListener('hardwareBackPress', onBackPress);
      return () => {
        subscription.remove();
      };
    }
  }, [visible, onClose]);

  // Stable callbacks so DrawerItem memo is not bypassed by new arrow functions
  const handleSelectAndClose = useCallback((id: string) => {
    onSelect(id);
    onClose();
  }, [onSelect, onClose]);

  // title_page and toc are auto-generated by the LaTeX backend — never editable.
  // Showing them as selectable would let users try to edit content that the
  // generator ignores, which is confusing. Match the web app's LeftPanel which
  // filters the same two IDs.
  const AUTO_SECTION_IDS = new Set(['title_page', 'toc']);
  const visibleFront = frontMatter.filter(s => !AUTO_SECTION_IDS.has(s.id));

  return (
    <View style={styles.container} pointerEvents={visible ? 'auto' : 'none'}>
      {/* Scrim */}
      <Animated.View style={[styles.scrim, { opacity }]}>
        <TouchableOpacity style={StyleSheet.absoluteFill} onPress={onClose} activeOpacity={1} />
      </Animated.View>

      {/* Drawer panel */}
      <Animated.View style={[styles.drawer, { transform: [{ translateX: slideX }] }]}>
        {/* Header */}
        <View style={styles.drawerHeader}>
          <Text style={styles.drawerTitle}>Document</Text>
          <TouchableOpacity onPress={onClose} hitSlop={8}>
            <Ionicons name="close" size={22} color={C.textMuted} />
          </TouchableOpacity>
        </View>

        <ScrollView
          style={styles.scroll}
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{ paddingBottom: S['3xl'] }}
        >
          {/* FRONT MATTER */}
          <SectionGroupLabel label="FRONT MATTER" />
          {visibleFront.map(s => (
            <DrawerItem
              key={s.id}
              label={s.label}
              icon={iconForSection(s.id)}
              isActive={activeId === s.id}
              hasContent={!!s.content}
              onPress={() => handleSelectAndClose(s.id)}
            />
          ))}

          {/* CHAPTERS */}
          <SectionGroupLabel label="CHAPTERS" style={{ marginTop: S.lg }} />
          {chapters.map((c, idx) => (
            <DrawerItem
              key={c.id}
              label={`${idx + 1}. ${c.title}`}
              icon="document-text-outline"
              isActive={activeId === c.id}
              hasContent={!!c.content}
              onPress={() => handleSelectAndClose(c.id)}
              onLongPress={() => onRenameChapter(c)}
              onDelete={c.required ? undefined : () => onDeleteChapter(c)}
            />
          ))}

          {/* Add chapter */}
          <TouchableOpacity
            onPress={onAddChapter}
            style={styles.addChapterBtn}
            activeOpacity={0.7}
          >
            <Ionicons name="add-circle-outline" size={18} color={C.accent} />
            <Text style={styles.addChapterText}>Add Chapter</Text>
          </TouchableOpacity>
        </ScrollView>
      </Animated.View>
    </View>
  );
}

// ── Helpers ────────────────────────────────────────────────────────────────────

// Module-level constant — never recreated, no allocation on render
const SECTION_ICONS: Record<string, string> = {
  title_page:      'home-outline',
  certificate:     'ribbon-outline',
  abstract:        'reader-outline',
  acknowledgement: 'heart-outline',
  toc:             'list-outline',
};

function iconForSection(id: string): string {
  return SECTION_ICONS[id] ?? 'document-outline';
}

// ── DrawerItem ─────────────────────────────────────────────────────────────────

const DrawerItem = memo(function DrawerItem({
  label, icon, isActive, hasContent,
  onPress, onLongPress, onDelete,
}: {
  label: string; icon: string; isActive: boolean; hasContent: boolean;
  onPress: () => void; onLongPress?: () => void; onDelete?: () => void;
}) {
  return (
    <TouchableOpacity
      onPress={onPress}
      onLongPress={onLongPress}
      activeOpacity={0.75}
      style={[styles.item, isActive && styles.itemActive]}
    >
      <View style={[styles.itemIconWrap, isActive && styles.itemIconActive]}>
        <Ionicons name={icon as any} size={16} color={isActive ? C.accent : C.textMuted} />
      </View>
      <Text style={[styles.itemLabel, isActive && styles.itemLabelActive]} numberOfLines={1}>
        {label}
      </Text>
      {hasContent && (
        <View style={[styles.dot, { backgroundColor: isActive ? C.accent : C.success }]} />
      )}
      {onDelete && (
        <TouchableOpacity onPress={onDelete} hitSlop={8} style={styles.deleteBtn}>
          <Ionicons name="trash-outline" size={14} color={C.textFaint} />
        </TouchableOpacity>
      )}
    </TouchableOpacity>
  );
});

// ── SectionGroupLabel ──────────────────────────────────────────────────────────

function SectionGroupLabel({ label, style }: { label: string; style?: object }) {
  return (
    <Text style={[styles.groupLabel, style]}>{label}</Text>
  );
}

// ── Styles ─────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 999,
  },
  scrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(44,42,38,0.5)',
  },
  drawer: {
    position: 'absolute',
    top: 0, bottom: 0, left: 0,
    width: DRAWER_W,
    backgroundColor: C.card,
    ...shadows.strong,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: S.lg,
    paddingTop: S['4xl'],
    paddingBottom: S.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.surface,
  },
  drawerTitle: { fontSize: F.lg, fontWeight: '800', color: C.text },
  scroll:      { flex: 1, paddingTop: S.sm },

  groupLabel: {
    fontSize: F.xs,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: C.textFaint,
    paddingHorizontal: S.lg,
    paddingVertical: S.xs,
    marginBottom: S.xs,
  },

  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: S.md,
    paddingVertical: S.md,
    paddingHorizontal: S.lg,
    marginHorizontal: S.sm,
    marginVertical: 1,
    borderRadius: R.lg,
  },
  itemActive: {
    backgroundColor: C.accentGlow,
    borderLeftWidth: 3,
    borderLeftColor: C.accent,
    paddingLeft: S.lg - 3,
  },
  itemIconWrap: {
    width: 30,
    height: 30,
    borderRadius: R.md,
    backgroundColor: C.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemIconActive: { backgroundColor: C.accentGlow },
  itemLabel:      { flex: 1, fontSize: F.sm, fontWeight: '500', color: C.textMuted },
  itemLabelActive:{ color: C.accent, fontWeight: '600' },
  dot:            { width: 7, height: 7, borderRadius: 4 },
  deleteBtn:      { padding: S.xs },

  addChapterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: S.sm,
    marginHorizontal: S.lg,
    marginTop: S.md,
    paddingVertical: S.md,
    paddingHorizontal: S.md,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: C.accentMid,
    borderRadius: R.lg,
    backgroundColor: C.accentGlow,
  },
  addChapterText: { fontSize: F.sm, fontWeight: '600', color: C.accent },
});
